---
title: "evidenciaFinal"
author: "Fernando Israel Rios Garcia"
date: "2023-04-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
2.	Calcula la longitud de las secuencias de cada variante.
3.	Crea una gráfica donde compares las bases de ADN que componen a cada una de las variantes del virus.
4.	¿Cuál es el %GC de cada variante?
5.	Crea las secuencias contrasentido de cada variante.

```{r}
lengthSeq <- function(dnaseq) {
  contador <- 0
  for (i in 1:length(dnaseq)) {
    contador <- contador + 1
  }
  return(contador)
}
```
```{r}
percentageGC <- function(dnaseq) {
  bases <- c("C", "G")
  c <- 0
  for(i in 1:length(bases)){
    contador <- 0
    for(j in 1:length(dnaseq)){
      if (bases [i] == dnaseq [j]){
        contador <- contador + 1
      }
    }
    amount <- contador*100/length(dnaseq)
    c <- amount + c    
  }
  print(paste0("GC : ", c, "%"))
}
}
```

```{r}
reverseSeq <- function(sequence) {
  reversed_sequence <- c()
  for (i in seq_len(nchar(sequence))) {
    reversed_sequence <- c(reversed_sequence, sequence[nchar(sequence) - i + 1])
  }
  return(reversed_sequence)
}
```

```{r}
countBases <- function(sequence) {
    count <
}
```

```{r}
library(seqinr)
library(ape)
AY2741193 <- read.fasta(file = AY2741193.fasta)
```